name: Test
on: [push,pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Lint
      uses: golangci/golangci-lint-action@v3

    - name: Run tests
      run: make test